spring:
  datasource:
    url: jdbc:mysql://数据库url:端口/数据库名?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: 数据库用户名
    password: 用户密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    hikari:
      max-lifetime: 1200000

  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 10MB

mybatis:
  # mybatis pageHelper 分页配置
  config-location: classpath:/config/SqlMapConfig.xml

server:
  port: 8080
  servlet:
    context-path: /base

## 开启 Swagger的 Basic认证功能,默认是false
swagger:
  # 是否关闭 swagger接口文档访问
  #  production: true
  basic:
    # 开启简单用户验证
    enable: true
    # 用户名
    username: base
    # 用户密码
    password: base

# 自定义 JWT key
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: base-ChlGPaXjNSit1wdUBQ0LXDfduI2mFZ
  # JWT的超期限时间(60*60*24 = 一天)
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer